name: Release
on:
  push:
    branches:
      - main
jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "feat!:"
          major_regexp_flags: ""
          minor_pattern: "feat:"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: ""
          namespace: portfolio
          bump_each_commit: false
          bump_each_commit_patch_pattern: ""
          search_commit_body: false
          user_format_type: "csv"
          enable_prerelease_mode: true
          debug: false
          version_from_branch: false
